include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_key_in_widget_constructors: ignore
    library_private_types_in_public_api: ignore
    sort_child_properties_last: ignore
    avoid_print: ignore
    file_names: ignore
    non_constant_identifier_names: ignore
    prefer_final_fields: ignore
    unused_import: ignore
    use_build_context_synchronously: ignore
    camel_case_types: ignore
    avoid_function_literals_in_foreach_calls: ignore
    sized_box_for_whitespace: ignore
    unused_label: ignore
